### ISSUE TITLE
logrotate no longer exists: 404

### ISSUE THREAD

**Issue by a-nldisr** [sheepkiller/rbd-docker-plugin-rpm#2]
wget -O ~/rpmbuild/SOURCES/rbd-docker-plugin_logrotate https://raw.githubusercontent.com/sheepkiller/rbd-docker-plugin/master/logrotate.d/rbd-docker-plugin_logrotate

HTTP request sent, awaiting response... 404 Not Found

Ended up here because i wanted to give the rpm build of the docker volume @ yp-engineering a try. Its mapped to your repo's, since you have this link in your dockerfile ill open this issue too.

**Comment by sheepkiller** [comment]
Hi Rogier, 

thanks for reporting the issue. It should be fixed now.

**Comment by a-nldisr** [comment]
Thanks for the super fast response!
